// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTu18SNNCFOzTuY-HeHJ34xk8LMy-riuw',
    appId: '1:317819475568:android:738c1e9d324e3536bb86b5',
    messagingSenderId: '317819475568',
    projectId: 'blink-a34ae',
    storageBucket: 'blink-a34ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSl3M5fv1FoWBjVu9hrovbH4pHryQhkxg',
    appId: '1:317819475568:ios:2468fa9469620332bb86b5',
    messagingSenderId: '317819475568',
    projectId: 'blink-a34ae',
    storageBucket: 'blink-a34ae.appspot.com',
    androidClientId: '317819475568-m51shhj986f6ktn970uu1vpv7jp9id98.apps.googleusercontent.com',
    iosClientId: '317819475568-ns5ilpgmn4kklp1vr44vp7oibohdcq5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );
}
